### ISSUE TITLE
在ptt市場的初步窺探.ipynb, pttData.csv 沒有['IP位置'], ['日期'] 兩個欄位 

### ISSUE THREAD

**Issue by paulyang0125** [HowardNTUST/Python-with-STP-Marketing-Strategy#2]
如題, 其導致ptt市場的初步窺探.ipynb中兩個章節 - ## 判斷發文IP位置 與 ## 發文時間 無法執行

請更新Google drive中的[PTT檔案](https://drive.google.com/file/d/1rKbeDzaU11GBPo2PaNGUQZV7EA-SKBSj/view?usp=sharing)

**Comment by derek890111** [comment]
同學您好：
非常感謝您的回覆，已更新Google drive中的[PTT檔案](https://drive.google.com/file/d/1t0cYLT8Z_zozxartwUxKpaVvuiEnm_fA/view?usp=sharing)，再請您確認看看。
若還有遇到疑問，歡迎在下方留言！非常感謝～

**Comment by paulyang0125** [comment]
收到 謝謝您
