### ISSUE TITLE
在ch8-7 目標選擇.ipynb 目錄缺少dict.txt.big, 另外其jieba.set_dictionary應修正

### ISSUE THREAD

**Issue by paulyang0125** [HowardNTUST/Python-with-STP-Marketing-Strategy#3]
請將ch8-8中的dict.txt.big.txt也複製到ch8-7目錄,另外jeba dictionary import應該修改成

`ieba.set_dictionary('dict.txt.big') -> jieba.set_dictionary('dict.txt.big.txt') `in 目標選擇.ipynb

**Comment by derek890111** [comment]
同學您好：
非常感謝您的回覆，已將「dict.txt.big」新增至ch8-7_目標選擇目錄，並更新程式碼，再請您確認看看。
若還有遇到疑問，歡迎在下方留言！非常感謝～

**Comment by paulyang0125** [comment]
收到 謝謝
