### ISSUE TITLE
缺少stopwords.txt in ch8-7_目標選擇目錄

### ISSUE THREAD

**Issue by paulyang0125** [HowardNTUST/Python-with-STP-Marketing-Strategy#4]
如題 請修改

**Comment by derek890111** [comment]
同學您好：
非常感謝您的回覆，已更新Google drive中的[PTT檔案](https://drive.google.com/file/d/1t0cYLT8Z_zozxartwUxKpaVvuiEnm_fA/view?usp=sharing)，再請您確認看看。
若還有遇到疑問，歡迎在下方留言！非常感謝～

**Comment by derek890111** [comment]
同學您好：
非常感謝您的回覆，已將「stopwords.txt檔」新增至ch8-7_目標選擇目錄，再請您確認看看。
若還有遇到疑問，歡迎在下方留言！非常感謝～

**Comment by paulyang0125** [comment]
收到 謝謝
